version: "3"

services:
  node:
    image: node:17.0.0-alpine
    user: node
    entrypoint: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    env_file: .env
    ports:
      - $SERVER_PORT:$SERVER_PORT
      - $CLIENT_PORT:$CLIENT_PORT
    volumes:
      - .:/home/node
    depends_on:
      - postgres
    networks:
      - mini-messenger

  postgres:
      image: postgres:13-alpine
      restart: always
      environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mini-messenger
          POSTGRES_USER: postgres
      volumes:
        - ./db-data-postgres:/var/lib/postgresql/data:rw
      ports:
        - target: 5432
          published: 5432
          protocol: tcp
      networks:
        - mini-messenger

  mongodb:
      image: mongo:4.2.1-bionic
      ports:
        - '27017:27017'
      volumes:
        - ./db-data-mongodb:/data/db
      networks:
        - mini-messenger

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - mini-messenger

networks:
  mini-messenger:
    driver: bridge